# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 12:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Source',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=250)),
                ('website', models.URLField(max_length=250)),
                ('rating_count', models.IntegerField()),
                ('avg_rating', models.FloatField()),
            ],
        ),
    ]
