# -*- coding: utf-8 -*-
# Generated by Django 1.9.4 on 2016-03-28 18:09
from __future__ import unicode_literals

import django.contrib.postgres.fields.jsonb
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('search', '0002_source'),
    ]

    operations = [
        migrations.AddField(
            model_name='searcher',
            name='preferences',
            field=django.contrib.postgres.fields.jsonb.JSONField(default={}),
        ),
    ]
